# version: '3'

# Declare the network at the top level
networks:
  app-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/db.sqlite:/app/db.sqlite
    networks:
      - app-network
    

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://18.219.239.1  # URL del backend en la red de Docker
    # volumes:
    #   - ./frontend/public:/app/public
    ports:
      - "80:3000"
    networks:
      - app-network
